### ISSUE TITLE
Default to onion IRC servers

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/joinmarket-webui-docker#24]
As pointed out in https://github.com/getumbrel/umbrel/issues/1300 the `standalone` image contains the default configuration which uses clearnet IRC servers.

Either consider adding an adapted configuration file or let the specific irc settings be replaced via environment variables (which can be done reliably for unique named config vars, but not for repeatedly used ones at the moment, e.g. `gaplimit` can be overridden, while `socks5_host` cannot be).

**Comment by kristapsk** [comment]
See also https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1061. It that is merged into JM, I see no problem in changing JM default config to use Tor by default.

**Comment by theborakompanioni** [comment]
> See also [JoinMarket-Org/joinmarket-clientserver#1061](https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1061). If that is merged into JM, I see no problem in changing JM default config to use Tor by default.

This is very good news. Thank you @kristapsk .

Just to clarify - as I see no changes to the default config - with this commit applied, every outgoing connection will be proxied via the local tor instance? Or is this preparing and installing tor and configs must still be adapted? (e.g. with https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1049)

**Comment by theborakompanioni** [comment]
Sentiment is still leaning towards an adapted config for now. Not happy with it, but we might be able to remove it later on. You should also take your time with your changes and there should be no time pressure on your side.

**Comment by kristapsk** [comment]
I don't feel any pressure. I have done coding work. But until somebody tests / reviews / ACKs it, it will not be merged.

Yes, as a fast solution you should edit config at your side for now.
